using System;
using System.Collections.Generic;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Web.Http;

namespace NumberToWordsApplication.Controllers
{
    /// <summary>
    /// Controller for the NumberToWords API.
    /// </summary>
    public class NumberToWordsController : ApiController
    {
        // api/NumberToWords/GetWords?input=
        public IHttpActionResult GetWords(string input)
        {
            try
            {
                // If input was valid, return the generated words.
                return Content(HttpStatusCode.OK, NumberToWords.Wordify(input));
            }
            catch (ArgumentException e)
            {
                // If input was not valid, return a bad request and the
                // error message generated by NumberToWords.
                return Content(HttpStatusCode.BadRequest, e.Message);
            }
        }
    }
}
